// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSoV60yvR4Q2F0NZ1oge-I6jmCJInoXlk',
    appId: '1:897863157413:web:9c54181938cad9b1432f4c',
    messagingSenderId: '897863157413',
    projectId: 'nestify-8f4b4',
    authDomain: 'nestify-8f4b4.firebaseapp.com',
    storageBucket: 'nestify-8f4b4.appspot.com',
    measurementId: 'G-HVSZQ4BY3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYnNKFtMLs5WSDV6CtoqrisOltM5Yb5s',
    appId: '1:897863157413:android:23a4fc9688cf2c73432f4c',
    messagingSenderId: '897863157413',
    projectId: 'nestify-8f4b4',
    storageBucket: 'nestify-8f4b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxHWRxYsn3kNf53DyWAbwEwIpBOuPkUg',
    appId: '1:897863157413:ios:e61bc94858a0adb5432f4c',
    messagingSenderId: '897863157413',
    projectId: 'nestify-8f4b4',
    storageBucket: 'nestify-8f4b4.appspot.com',
    iosBundleId: 'com.example.nestify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXxHWRxYsn3kNf53DyWAbwEwIpBOuPkUg',
    appId: '1:897863157413:ios:e61bc94858a0adb5432f4c',
    messagingSenderId: '897863157413',
    projectId: 'nestify-8f4b4',
    storageBucket: 'nestify-8f4b4.appspot.com',
    iosBundleId: 'com.example.nestify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSoV60yvR4Q2F0NZ1oge-I6jmCJInoXlk',
    appId: '1:897863157413:web:7920f20c95e90f69432f4c',
    messagingSenderId: '897863157413',
    projectId: 'nestify-8f4b4',
    authDomain: 'nestify-8f4b4.firebaseapp.com',
    storageBucket: 'nestify-8f4b4.appspot.com',
    measurementId: 'G-BMS66CW72J',
  );
}
